### PR TITLE
refactor: convert to Go modules

### PR DESCRIPTION
**Pull request by ash2k**
This also bumps Kubernetes dependencies to match gitops-engine.

I'm using gitops-engine, which depends on this package. Because of old dependencies here, Go tries to bring weird versions of them. Just trying to fix that.

Ideally gitops-engine maybe could drop dependency on this package because the usage is insignificant and is probably not worth an extra dependency.

@alexmt

### CODE REVIEW

**Comment by alexec** [comment]
@jessesuen @ash2k I'm having problems after these changes: 

```
go: github.com/argoproj/pkg@v0.0.0-20200424003221-9b858eff18a1 requires
	k8s.io/api@v1.17.8: reading k8s.io/api/go.mod at revision v1.17.8: unknown revision v1.17.8
```

**Comment by alexec** [comment]
```
go: github.com/argoproj/pkg@v0.0.0-20200424003221-9b858eff18a1 requires
	k8s.io/api@v1.17.8: reading k8s.io/api/go.mod at revision v1.17.8: unknown revision v1.17
```

**Comment by alexec** [comment]
Both workflows and events use v0.17.5 not v0.17.8.

**Comment by ash2k** [comment]
@alexec to resolve the issue please copy the `replace` block from this PR into the other projects. This is annoying, but this is how go modules work.

**Pull request merged**
