### PR TITLE
feat: use RWMutex in KeyLock to support more use cases

### PR DESCRIPTION
**Pull request by yujunz**
RWMutex will perform better for read heavy use cases

### CODE REVIEW

**Comment by yujunz** [comment]
One typical use case is project lock in application operations. See https://github.com/yujunz/argo-cd/commit/cfc5c27c00e15e13e057a7a2c927f72e94906f83

The project lock seems slowing down `argocd app set` actions a lot when many applications are in the same project. It sometimes timeout at 90s per our observation on 90 applications in one project. RLock will allow much higher concurrency in this use case.

**Comment by alexec** [comment]
@alexmt can you please review?

**Review by alexec — APPROVED** [review]

**Comment by yujunz** [comment]
@alexec any actions required from me to get it merged?

**Review by alexmt — APPROVED** [review]
LGTM

**Pull request merged**
