### PR TITLE
Use more up-to-date and comprehensive JSONPath library

### PR DESCRIPTION
**Pull request by b-erdem**
Recently we noticed that Argo Workflow doesn't support some JSONPath expression to extract some values from inputs. After digging a bit we found that current JSONPath library used by Argo is outdated and it does support only a fraction of the spec. After looking around for better JSONPath libraries I found this one that works for the all expressions I have tried so far: github.com/evilmonkeyinc/jsonpath

If you're also curious about other libraries you can see a comparison here but keep in mind that it's either outdated or incorrect: https://asaiyusuke.github.io/jsonpath/cburgmer-json-path-comparison/docs/index.html

Because I tried some of the JSONPath libraries listed there, including the one written by the author of the post above and most of the expressions in the comparison table didn't work. 

* As I see these changes don't cause any issue or break existing functionality. 

* I have added some test cases to cover more complex expressions.

Please let me know if there's any mistake or something I'm missing when opening a PR here.

### CODE REVIEW

**Comment by b-erdem** [comment]
@agilgur5 Hello Anton, I opened this PR to change the JSONPath library.

**Comment by agilgur5** [comment]
For posterity, this is a follow-up [from Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1692364134024219?thread_ts=1692364134.024219&cid=C01QW9QSSSK)

**Review by agilgur5 — APPROVED** [review]
LGTM. Thanks for adding tests too!

**Comment by agilgur5** [comment]
I looked through some of the Go JSONPath libraries as well and noticed that several were unmaintained (and incomplete) unfortunately 😕
The new library in this PR is not that popular, but none of them really were as far as I could tell. This one does have some decent docs though

**Review by terrytangyuan — APPROVED** [review]

**Comment by agilgur5** [comment]
@b-erdem could you make a PR to Workflows to update this dep now?

**Comment by b-erdem** [comment]
> @b-erdem could you make a PR to Workflows to update this dep now?

Hi, thanks for merging it! I can open a PR on Workflows in a few hours once I’m at home. Does that work?

**Comment by agilgur5** [comment]
Yea no rush or anything

**Comment by agilgur5** [comment]
@b-erdem just a friendly reminder that the full update still requires a PR to Workflows

**Comment by b-erdem** [comment]
@agilgur5 Thanks for the reminder. I’m working on it. It turned out I needed to make a few changes on the main repo. Just updating the dependencies was not enough. I’ll just open a PR and we can discuss the changes I made there.

**Pull request merged**
