### PR TITLE
refactor(deps): upgrade to `aws-sdk-go-v2`

### PR DESCRIPTION
**Pull request by agilgur5**
Partial fix for https://github.com/argoproj/argo-workflows/issues/12031, Vulnerabilities
- `aws-sdk-go` v1 is only used [from `pkg`](https://github.com/argoproj/argo-workflows/blob/abf983651b35c301b3f37a4b9518ed68282a2e76/workflow/artifacts/s3/s3.go#L12) for Workflows

## Motivation

- `aws-sdk-go` has [a vuln](https://osv.dev/vulnerability/GO-2022-0646) in the v1 EncryptionClient
  - it's fixed in the v2 client
  - we don't use this functionality, but still get reported this vuln
    - instead of adding an ignore for the vuln, figured I might as well make the upgrade to v2

## Modifications

- follow the [migration instructions](https://aws.github.io/aws-sdk-go-v2/docs/migrating/)
  - migrate all `session` usage to `config.LoadDefaultConfig` per [instructions](https://aws.github.io/aws-sdk-go-v2/docs/migrating/#configuration-loading)
    - this includes shared config handling, so I believe `session.SharedConfigEnable` is no longer necessary per [instructions](https://aws.github.io/aws-sdk-go-v2/docs/migrating/#migrating-from-newsessionwithoptions)
      - the docs on ["Speciyfing Credentials"](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#specifying-credentials) seem to state this as well, if I'm understanding correctly
    - see also `config.WithRegion` mention in the [instructions](https://aws.github.io/aws-sdk-go-v2/docs/migrating/#migrating-from-newsession-with-awsconfig-options)
  - migrate credential usage
    - [`Config.Credentials`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws#Config) still exists, but the function is now [`Retrieve(context)`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws#CredentialsProvider) instead of `Get`
      - the [`Credentials` struct](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws#Credentials) otherwise looks the same, has the `AccessKeyId`, `SecretAccessKey`, and `SessionToken` that were used in v1
    - STS credentials are retrieved a bit differently now [per instructions](https://aws.github.io/aws-sdk-go-v2/docs/migrating/#aws-security-token-service-credentials)
      - use a `config` instead of a `session` to create a client, then use `NewAssumeRoleProvider` instead of `NewCredentials

- NOTE: I used `context.Background()` for all of the contexts that are now required
  - it may make more sense for context to be passed into these functions, but that would be a breaking change and require downstream changes in Argo projects, so I left that out for now and just went with `Background` as a default
  - see also https://github.com/aws/aws-sdk-go-v2/issues/1272
  
## Verification

- confirmed that `go.mod` has latest versions (e.g. `config` [released v1.19.0](https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2023-10-16) this week)
- Tested `make build` and `make test` pass successfully. Did not test this live however as that needs to be done downstream

### CODE REVIEW

**Review by jmeridth — APPROVED** [review]

**Review by terrytangyuan — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@agilgur5 can you rebase?

**Comment by agilgur5** [comment]
Aw dang, another conflict with dependabot. Fixed conflicts now if we could get this in before the next conflict 😅

**Comment by agilgur5** [comment]
There an `aws-sdk-go` bump like every other day apparently; the large majority of PRs in this repo are actually from [`aws-sdk-go` bumps](https://github.com/argoproj/pkg/pulls?q=is%3Apr+is%3Aclosed+aws-sdk-go)

**Comment by agilgur5** [comment]
3rd+ merge conflict fixed now 😕 

@terrytangyuan @crenshaw-dev could either of you merge this? it will conflict with dependabot about every other day per above

**Pull request merged**
